name: stockify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
   #state management 
   #https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.6.1 

  #navigation 
  #https://pub.dev/packages/go_router
  go_router: ^15.0.0 

  #networking - untuk buat API client yg clean & auto-generate dari interface
  #https://pub.dev/packages/retrofit
  retrofit: ^4.4.2

  #networking - http client powerful untuk handle request/response
  #https://pub.dev/packages/dio
  dio: ^5.8.0+1

  #format log request & response dari dio biar lebih enak dibaca
  #https://pub.dev/packages/dio_http_formatter
  dio_http_formatter: ^3.3.0

  ##annotation untuk bikin data class immutable dan union type (dipakai bareng freezed)
  #https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^3.0.0

  #annotation untuk bantu generate model dari JSON
  #https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0

  #library untuk format tanggal, angka, dan localization
  #https://pub.dev/packages/intl
  intl: ^0.20.2
  #https://pub.dev/packages/multiple_result
  multiple_result: ^5.1.0

  #https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1

  flutter_spinkit: ^5.2.1
  jwt_decoder: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
   #tool utama buat generate file (dipake bareng generator lain)
  #https://pub.dev/packages/build_runner
  build_runner: ^2.4.15

  #generator untuk retrofit - auto generate API client dari interface
  #https://pub.dev/packages/retrofit_generator
  retrofit_generator: ^9.1.9

  #generator untuk json_serializable - generate toJson/fromJson
  #https://pub.dev/packages/json_serializable
  json_serializable: ^6.9.4

  #generator buat freezed - auto generate data class & union
  #https://pub.dev/packages/freezed
  freezed: ^3.0.6

  #generator untuk riverpod - bantu generate provider & anotasi otomatis
  #https://pub.dev/packages/riverpod_generator
  riverpod_generator: ^2.6.5
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
